# Generated by Django 3.2.20 on 2024-02-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_auto_20240206_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='user',
            new_name='members',
        ),
    ]
