# Generated by Django 3.2.20 on 2024-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_rename_user_university_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='team',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
