# Generated by Django 5.0.2 on 2024-02-26 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0009_alter_university_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='members',
            field=models.ManyToManyField(related_name='university_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=200)),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='custom_user.university')),
            ],
        ),
    ]
