# Generated by Django 5.0.2 on 2024-02-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_rename_members_team_members_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='teams',
            field=models.ManyToManyField(related_name='university_members', to='custom_user.team'),
        ),
    ]
