# Generated by Django 5.0.2 on 2024-02-26 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0013_remove_team_university_university_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='leader',
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
