# Generated by Django 3.2.20 on 2024-09-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0014_remove_university_leader_team_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp_1_hability', models.CharField(blank=True, max_length=200)),
                ('time_stamp_2_hability', models.CharField(blank=True, max_length=200)),
                ('time_stamp_1_acceleration', models.CharField(blank=True, max_length=200)),
                ('time_stamp_2_acceleration', models.CharField(blank=True, max_length=200)),
                ('time_stamp_1_gp', models.CharField(blank=True, max_length=200)),
                ('time_stamp_2_gp', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='custom_user.team')),
            ],
        ),
    ]
