# Generated by Django 3.2.20 on 2024-10-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0017_alter_timestamps_total_time_hability'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='eff_gp',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
