# Generated by Django 3.2.20 on 2024-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0019_timestamps_global_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='total_time_aceleration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timestamps',
            name='total_time_aceleration_2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='timestamps',
            name='total_time_hability_2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
