# Generated by Django 3.2.20 on 2024-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0021_timestamps_total_position_acel'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='total_penalization_acel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
